app/controllers/application_controller.rb
db/migrate/20220228160352_add_first_name_last_name_username_expert_to_users.rb
db/schema.rb

added username first_name last_name expert attributes for user

User model

---

app/controllers/bookings_controller.rb
app/views/bookings/new.html.erb
config/routes.rb

routes fixed

---

app/controllers/evaluations_controller.rb
app/models/evaluation.rb
app/views/evaluations/new.html.erb
config/routes.rb
db/schema.rb
test/controllers/evaluations_controller_test.rb

Added create and show evaluation to Evaluations controller and the routes

Evaluations

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

needs some styling more but the main idea is there

searchbar semi compleet for home page

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_bookings-card.scss
app/assets/stylesheets/components/_cta-button.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_searchbar.scss
app/assets/stylesheets/components/_service_card.scss
app/assets/stylesheets/config/_colors.scss
app/views/services/new.html.erb

Consistency

---

app/views/services/wheelpers.html.erb
app/views/shared/_index_page_card.html.erb

added links to cards

---

app/controllers/bookings_controller.rb

fixed link on services to book

link for booking page

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_map.scss
app/javascript/controllers/index.js
app/javascript/packs/booking_new.js
app/views/bookings/new.html.erb
app/views/services/index.html.erb
app/views/services/wheelpers.html.erb
db/seeds.rb
package.json
yarn.lock

calendar for input form and sticky map

Availability format

---

app/views/shared/_availability.html.erb
app/views/shared/_index_page_card.html.erb

availability for the next 7 days displayed on the card

Daysofweek

---

app/assets/stylesheets/components/_map.scss
app/javascript/controllers/flatpickr_booking_form_controller.js
app/views/bookings/new.html.erb
app/views/services/index.html.erb

stimulus syntax fixed

---

app/assets/stylesheets/components/_navbar.scss
app/javascript/controllers/flatpickr_booking_form_controller.js
app/views/services/index.html.erb
app/views/services/new.html.erb
app/views/shared/_dashboard_expert.html.erb
app/views/shared/_navbar.html.erb

navbar fixes and stimulus service#new fix

Navbar toggle

---

app/views/services/index.html.erb
app/views/shared/_index_page_card.html.erb

render fixed to add locals

---

app/controllers/bookings_controller.rb
app/controllers/services_controller.rb
app/views/services/new.html.erb
app/views/shared/_booking_dashboard_card_customer.html.erb
app/views/shared/_booking_dashboard_card_expert.html.erb
app/views/shared/_dashboard_customer.html.erb
app/views/shared/_dashboard_expert.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb

Booking edits

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_map.scss
app/controllers/services_controller.rb
app/javascript/controllers/geocoder_controller.js
app/javascript/controllers/mapbox_controller.js
app/views/bookings/new.html.erb
app/views/services/index.html.erb
app/views/services/new.html.erb

geocoder inputs for new services and bookings

New service

---

app/assets/stylesheets/config/_bootstrap_variables.scss

 fixed boostrap variables

---

app/views/services/show.html.erb
app/views/shared/_image_links.html.erb

Image upload

---

app/assets/stylesheets/components/_bookings-card.scss
app/views/bookings/_booking_dashboard_card_customer.html.erb
app/views/bookings/_dashboard_customer.html.erb
app/views/shared/_footer.html.erb

adding dates to booking card and adding three categories - pending, evaluated and rejected

adding booking categories and dates

---

app/assets/stylesheets/components/_cta-button.scss

fixed error

---

app/assets/stylesheets/components/_cta-button.scss
app/views/shared/_banner.html.erb

button classes

---

app/models/service.rb
db/seeds.rb

Validations for services and seeds fix

Validations for services and seeds fix

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_reviews-card.scss
app/controllers/application_controller.rb
app/models/user.rb
app/views/reviews/_reviews-card.erb
app/views/services/show.html.erb
app/views/shared/_index_page_card.html.erb
app/views/shared/_navbar.html.erb
db/seeds.rb

added avatars to seeds file, attached photo to user and used the avatar across the webpage

Seedsphotos

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_bookings-card.scss
app/views/bookings/_booking_dashboard_card_customer.html.erb
app/views/bookings/_booking_dashboard_card_expert.html.erb
app/views/bookings/_dashboard_customer.html.erb
app/views/bookings/_dashboard_expert.html.erb

adjusted date to english version, styling dashboards for expert and customers, removed underlines, centred info - still more to be done!!

styling dashboard

---

app/views/bookings/_dashboard_customer.html.erb
app/views/bookings/_dashboard_expert.html.erb

ends fixed on dashboard

---

app/assets/stylesheets/components/_frame.scss
app/assets/stylesheets/components/_reviews-card.scss
app/assets/stylesheets/components/_service-type-card.scss

Spacing on info cards on show page

Put spacing in review cards on show page

---

app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_frame.scss
app/assets/stylesheets/components/_searchbar.scss
app/views/shared/_search_bar.html.erb

search bar fixed to navbar styled

Fontawesome

---

app/assets/stylesheets/components/_form.scss
app/views/services/_search-bar-wheelpers.html.erb
app/views/services/wheelpers.html.erb
app/views/shared/_navbar.html.erb

put the search bar functioning html in a separated html file, we are not rendering it

New search bar
